#!/usr/bin/env python3
"""Generate the original, fictional SkunkWorks sensor-mount demo packet.

Only Python's standard library is used. The portable manifest and PDF share
one parameter table; the GLB is a self-contained, metre-scaled rigid-panel
assembly generated by applying the same signed hinge rotations.
"""
from __future__ import annotations

import json
import math
import struct
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[4]
OUTPUT = ROOT / "public" / "demo"
OUTPUT.mkdir(parents=True, exist_ok=True)


def rect(panel_id: str, x0: float, y0: float, x1: float, y1: float) -> dict[str, Any]:
    return {
        "id": panel_id,
        "polygonMm": [[x0, y0], [x1, y0], [x1, y1], [x0, y1]],
    }


def variant(variant_id: str) -> dict[str, Any]:
    if variant_id == "alpha":
        width, height = 120.0, 80.0
        left_depth, return_depth, right_depth = 25.0, 18.0, 26.0
        top_width, top_depth = 40.0, 20.0
        bottom_width, bottom_depth = 30.0, 18.0
        thickness = 2.0
        rotations = {"B1": 90.0, "B2": -90.0, "B3": -90.0, "B4": 90.0, "B5": -90.0}
        order = ["B1", "B3", "B4", "B5", "B2"]
        part_number, revision = "SKW-SM-104", "A"
    elif variant_id == "bravo":
        width, height = 148.0, 86.0
        left_depth, return_depth, right_depth = 32.0, 22.0, 30.0
        top_width, top_depth = 50.0, 24.0
        bottom_width, bottom_depth = 36.0, 22.0
        thickness = 2.5
        rotations = {"B1": 90.0, "B2": -90.0, "B3": 90.0, "B4": 90.0, "B5": -90.0}
        order = ["B3", "B1", "B5", "B2", "B4"]
        part_number, revision = "SKW-SM-205", "B"
    else:
        raise ValueError("Unknown demo variant: " + variant_id)

    top_x0 = (width - top_width) / 2
    top_x1 = top_x0 + top_width
    bottom_x0 = (width - bottom_width) / 2
    bottom_x1 = bottom_x0 + bottom_width
    left_outer = -left_depth
    return_outer = left_outer - return_depth

    panels = [
        rect("base", 0, 0, width, height),
        rect("left-flange", left_outer, 0, 0, height),
        rect("left-return", return_outer, 0, left_outer, height),
        rect("right-flange", width, 0, width + right_depth, height),
        rect("top-tab", top_x0, height, top_x1, height + top_depth),
        rect("bottom-tab", bottom_x0, -bottom_depth, bottom_x1, 0),
    ]
    hinges = [
        {"id": "hinge-b1-left", "parentPanelId": "base", "childPanelId": "left-flange",
         "axisStartMm": [0, 0], "axisEndMm": [0, height]},
        {"id": "hinge-b2-return", "parentPanelId": "left-flange", "childPanelId": "left-return",
         "axisStartMm": [left_outer, 0], "axisEndMm": [left_outer, height]},
        {"id": "hinge-b3-right", "parentPanelId": "base", "childPanelId": "right-flange",
         "axisStartMm": [width, 0], "axisEndMm": [width, height]},
        {"id": "hinge-b4-top", "parentPanelId": "base", "childPanelId": "top-tab",
         "axisStartMm": [top_x0, height], "axisEndMm": [top_x1, height]},
        {"id": "hinge-b5-bottom", "parentPanelId": "base", "childPanelId": "bottom-tab",
         "axisStartMm": [bottom_x0, 0], "axisEndMm": [bottom_x1, 0]},
    ]
    bend_mappings = [
        {"bendId": "B1", "hingeId": "hinge-b1-left", "foldRotationDeg": rotations["B1"],
         "finishedAngle": {"degrees": 90, "convention": "internal"}},
        {"bendId": "B2", "hingeId": "hinge-b2-return", "foldRotationDeg": rotations["B2"],
         "finishedAngle": {"degrees": 90, "convention": "internal"}},
        {"bendId": "B3", "hingeId": "hinge-b3-right", "foldRotationDeg": rotations["B3"],
         "finishedAngle": {"degrees": 90, "convention": "internal"}},
        {"bendId": "B4", "hingeId": "hinge-b4-top", "foldRotationDeg": rotations["B4"],
         "finishedAngle": {"degrees": 90, "convention": "internal"}},
        {"bendId": "B5", "hingeId": "hinge-b5-bottom", "foldRotationDeg": rotations["B5"],
         "finishedAngle": {"degrees": 90, "convention": "internal"}},
    ]
    panel_model = {
        "schemaVersion": "1.0",
        "units": "mm",
        "thicknessMm": thickness,
        "rootPanelId": "base",
        "panels": panels,
        "hinges": hinges,
        "origin": "authored_manifest",
        "referenceFaceLabel": "Outside face",
        "reviewed": True,
    }
    return {
        "manifestVersion": "skunkworks-bend-manifest/1.0",
        "part": {
            "partNumber": part_number,
            "drawingRevision": revision,
            "name": "Sensor mount - synthetic demonstration",
            "partFamily": "single-sheet-straight-bend-bracket",
        },
        "panelModel": panel_model,
        "bendMappings": bend_mappings,
        "stepOrder": order,
        "provenance": {
            "source": "Original synthetic artwork generated for the SkunkWorks prototype",
            "authorship": "Explicitly authored demonstration geometry; not customer data",
            "intendedUse": "Interface and geometry verification only; not for production",
            "coordinateConvention": "Millimetres; +Z points toward the reference face; positive rotation follows the right-hand rule about each directed hinge axis",
        },
    }


def multiply(a: list[float], b: list[float]) -> list[float]:
    result = [0.0] * 16
    for column in range(4):
        for row in range(4):
            result[column * 4 + row] = sum(a[index * 4 + row] * b[column * 4 + index] for index in range(4))
    return result


def hinge_matrix(hinge: dict[str, Any], degrees: float) -> list[float]:
    sx, sy = hinge["axisStartMm"]
    ex, ey = hinge["axisEndMm"]
    length = math.hypot(ex - sx, ey - sy)
    x, y = (ex - sx) / length, (ey - sy) / length
    z = 0.0
    angle = math.radians(degrees)
    c, s, t = math.cos(angle), math.sin(angle), 1 - math.cos(angle)
    r00, r01, r02 = c + x*x*t, x*y*t - z*s, x*z*t + y*s
    r10, r11, r12 = y*x*t + z*s, c + y*y*t, y*z*t - x*s
    r20, r21, r22 = z*x*t - y*s, z*y*t + x*s, c + z*z*t
    rotated = (r00*sx + r01*sy, r10*sx + r11*sy, r20*sx + r21*sy)
    return [
        r00, r10, r20, 0,
        r01, r11, r21, 0,
        r02, r12, r22, 0,
        sx - rotated[0], sy - rotated[1], -rotated[2], 1,
    ]


def transform(matrix: list[float], point: tuple[float, float, float]) -> tuple[float, float, float]:
    x, y, z = point
    return (
        matrix[0]*x + matrix[4]*y + matrix[8]*z + matrix[12],
        matrix[1]*x + matrix[5]*y + matrix[9]*z + matrix[13],
        matrix[2]*x + matrix[6]*y + matrix[10]*z + matrix[14],
    )


def final_transforms(packet: dict[str, Any]) -> dict[str, list[float]]:
    model = packet["panelModel"]
    hinges = model["hinges"]
    bend_to_hinge = {bend["bendId"]: bend["hingeId"] for bend in packet["bendMappings"]}
    rotation_by_hinge = {bend["hingeId"]: bend["foldRotationDeg"] for bend in packet["bendMappings"]}
    del bend_to_hinge  # Mapping is preserved in the portable manifest; final mesh folds every authored bend.
    children: dict[str, list[dict[str, Any]]] = {}
    for hinge in hinges:
        children.setdefault(hinge["parentPanelId"], []).append(hinge)
    poses: dict[str, list[float]] = {}

    def visit(panel_id: str, parent_pose: list[float]) -> None:
        poses[panel_id] = parent_pose
        for hinge in children.get(panel_id, []):
            angle = rotation_by_hinge.get(hinge["id"], 0.0)
            visit(hinge["childPanelId"], multiply(parent_pose, hinge_matrix(hinge, angle)))

    visit(model["rootPanelId"], [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1])
    return poses


def triangle_data(packet: dict[str, Any]) -> tuple[list[float], list[float]]:
    model = packet["panelModel"]
    transforms = final_transforms(packet)
    half_thickness = model["thicknessMm"] / 2
    positions: list[float] = []
    normals: list[float] = []

    def emit_triangle(panel_id: str, points: list[tuple[float, float, float]], normal: tuple[float, float, float]) -> None:
        pose = transforms[panel_id]
        world_normal = (
            pose[0]*normal[0] + pose[4]*normal[1] + pose[8]*normal[2],
            pose[1]*normal[0] + pose[5]*normal[1] + pose[9]*normal[2],
            pose[2]*normal[0] + pose[6]*normal[1] + pose[10]*normal[2],
        )
        norm_len = math.sqrt(sum(value*value for value in world_normal)) or 1.0
        unit_normal = tuple(value / norm_len for value in world_normal)
        for point in points:
            world = transform(pose, point)
            positions.extend(value * 0.001 for value in world)
            normals.extend(unit_normal)

    for panel in model["panels"]:
        points = [tuple(point) for point in panel["polygonMm"]]
        # The authored sample polygons are convex rectangles, so a fan is a valid triangulation.
        for index in range(1, len(points) - 1):
            emit_triangle(panel["id"], [
                (points[0][0], points[0][1], half_thickness),
                (points[index][0], points[index][1], half_thickness),
                (points[index + 1][0], points[index + 1][1], half_thickness),
            ], (0, 0, 1))
            emit_triangle(panel["id"], [
                (points[0][0], points[0][1], -half_thickness),
                (points[index + 1][0], points[index + 1][1], -half_thickness),
                (points[index][0], points[index][1], -half_thickness),
            ], (0, 0, -1))
        for index, start in enumerate(points):
            end = points[(index + 1) % len(points)]
            dx, dy = end[0] - start[0], end[1] - start[1]
            edge_length = math.hypot(dx, dy)
            normal = (dy / edge_length, -dx / edge_length, 0)
            a = (start[0], start[1], -half_thickness)
            b = (end[0], end[1], -half_thickness)
            c = (end[0], end[1], half_thickness)
            d = (start[0], start[1], half_thickness)
            emit_triangle(panel["id"], [a, b, c], normal)
            emit_triangle(panel["id"], [a, c, d], normal)
    return positions, normals


def write_glb(path: Path, packet: dict[str, Any]) -> None:
    positions, normals = triangle_data(packet)
    position_bytes = struct.pack("<" + "f" * len(positions), *positions)
    normal_bytes = struct.pack("<" + "f" * len(normals), *normals)
    binary = position_bytes + normal_bytes
    binary += b"\0" * ((4 - len(binary) % 4) % 4)
    vertex_count = len(positions) // 3
    min_pos = [min(positions[index::3]) for index in range(3)]
    max_pos = [max(positions[index::3]) for index in range(3)]
    document = {
        "asset": {"version": "2.0", "generator": "SkunkWorks original synthetic demo asset generator"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "name": packet["part"]["partNumber"] + " reviewed panel model"}],
        "meshes": [{"name": "Rigid panel bend diagram final model", "primitives": [{
            "attributes": {"POSITION": 0, "NORMAL": 1},
            "material": 0,
            "mode": 4,
        }]}],
        "materials": [{"name": "Neutral workshop aluminium", "doubleSided": True,
                       "pbrMetallicRoughness": {"baseColorFactor": [0.70, 0.74, 0.77, 1],
                                                "metallicFactor": 0.28, "roughnessFactor": 0.48}}],
        "buffers": [{"byteLength": len(binary)}],
        "bufferViews": [
            {"buffer": 0, "byteOffset": 0, "byteLength": len(position_bytes), "target": 34962},
            {"buffer": 0, "byteOffset": len(position_bytes), "byteLength": len(normal_bytes), "target": 34962},
        ],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": vertex_count, "type": "VEC3", "min": min_pos, "max": max_pos},
            {"bufferView": 1, "componentType": 5126, "count": vertex_count, "type": "VEC3"},
        ],
        "extras": {
            "partNumber": packet["part"]["partNumber"],
            "drawingRevision": packet["part"]["drawingRevision"],
            "sourceUnits": "mm",
            "glbUnits": "m",
            "conversion": "1 mm = 0.001 m",
            "authorship": "Original synthetic demonstration model; not production geometry",
        },
    }
    json_chunk = json.dumps(document, separators=(",", ":"), ensure_ascii=True).encode("utf-8")
    json_chunk += b" " * ((4 - len(json_chunk) % 4) % 4)
    binary_chunk = binary
    total_length = 12 + 8 + len(json_chunk) + 8 + len(binary_chunk)
    with path.open("wb") as file:
        file.write(struct.pack("<4sII", b"glTF", 2, total_length))
        file.write(struct.pack("<I4s", len(json_chunk), b"JSON"))
        file.write(json_chunk)
        file.write(struct.pack("<I4s", len(binary_chunk), b"BIN\0"))
        file.write(binary_chunk)


def pdf_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def pdf_text(x: float, y: float, text: str, size: float = 10, color: tuple[float, float, float] = (0.12, 0.17, 0.21)) -> str:
    r, g, b = color
    return f"{r:.3f} {g:.3f} {b:.3f} rg BT /F1 {size:.1f} Tf {x:.2f} {y:.2f} Td ({pdf_escape(text)}) Tj ET\n"


def pdf_line(x1: float, y1: float, x2: float, y2: float, color: tuple[float, float, float], width: float = 0.8) -> str:
    r, g, b = color
    return f"{r:.3f} {g:.3f} {b:.3f} RG {width:.2f} w {x1:.2f} {y1:.2f} m {x2:.2f} {y2:.2f} l S\n"


def pdf_rect(points: list[list[float]], origin_x: float, origin_y: float, scale: float) -> str:
    coords = [(origin_x + point[0] * scale, origin_y + point[1] * scale) for point in points]
    commands = f"{coords[0][0]:.2f} {coords[0][1]:.2f} m\n"
    for x, y in coords[1:]:
        commands += f"{x:.2f} {y:.2f} l\n"
    commands += "h\n0.28 0.32 0.35 RG 1.1 w 0.90 0.91 0.90 rg B\n"
    return commands


def make_pdf(packet: dict[str, Any], path: Path) -> None:
    page_width, page_height = 612.0, 792.0
    all_x = [point[0] for panel in packet["panelModel"]["panels"] for point in panel["polygonMm"]]
    min_panel_x, max_panel_x = min(all_x), max(all_x)
    flat_width = max_panel_x - min_panel_x
    scale = min(2.1, (page_width - 84) / flat_width)
    origin_x = (page_width - flat_width * scale) / 2 - min_panel_x * scale
    origin_y = 430.0
    content = ""
    content += pdf_text(42, 748, "SKUNKWORKS  /  PROTOTYPE HANDOFF", 9, (0.16, 0.34, 0.46))
    content += pdf_text(42, 715, "SENSOR MOUNT - " + packet["part"]["partNumber"], 19)
    content += pdf_text(42, 693, "Drawing revision " + packet["part"]["drawingRevision"] + "   |   Flat blank mapping", 10)
    content += pdf_text(42, 670, "SYNTHETIC EXAMPLE - NOT FOR PRODUCTION", 10, (0.68, 0.26, 0.12))
    content += pdf_text(42, 647, "Top view of flat panel layout; bend IDs match the reviewed bend manifest.", 9, (0.31, 0.36, 0.39))

    for panel in packet["panelModel"]["panels"]:
        content += pdf_rect(panel["polygonMm"], origin_x, origin_y, scale)

    blue = (0.08, 0.35, 0.72)
    bend_centers: dict[str, tuple[float, float]] = {}
    for bend in packet["bendMappings"]:
        hinge = next(item for item in packet["panelModel"]["hinges"] if item["id"] == bend["hingeId"])
        sx, sy = hinge["axisStartMm"]
        ex, ey = hinge["axisEndMm"]
        x1, y1 = origin_x + sx * scale, origin_y + sy * scale
        x2, y2 = origin_x + ex * scale, origin_y + ey * scale
        content += pdf_line(x1, y1, x2, y2, blue, 2.1)
        bend_centers[bend["bendId"]] = ((x1 + x2) / 2, (y1 + y2) / 2)
    for bend_id, (x, y) in bend_centers.items():
        content += f"{blue[0]:.3f} {blue[1]:.3f} {blue[2]:.3f} rg {x-10:.2f} {y+6:.2f} 20 13 re f\n"
        content += pdf_text(x - 6.5, y + 9, bend_id, 7, (1, 1, 1))

    # A compact dimensions block presents actual authored blank dimensions.
    width = max(point[0] for panel in packet["panelModel"]["panels"] for point in panel["polygonMm"])
    min_x = min(point[0] for panel in packet["panelModel"]["panels"] for point in panel["polygonMm"])
    max_y = max(point[1] for panel in packet["panelModel"]["panels"] for point in panel["polygonMm"])
    min_y = min(point[1] for panel in packet["panelModel"]["panels"] for point in panel["polygonMm"])
    content += pdf_text(42, 305, "FLAT LAYOUT REFERENCE", 9, (0.16, 0.34, 0.46))
    content += pdf_text(42, 286, "Overall blank width: " + f"{width-min_x:.0f}" + " mm", 10)
    content += pdf_text(42, 269, "Overall blank height: " + f"{max_y-min_y:.0f}" + " mm", 10)
    content += pdf_text(42, 252, "Material thickness: " + f"{packet['panelModel']['thicknessMm']:.1f}" + " mm", 10)
    content += pdf_text(42, 225, "BEND TARGETS (internal angle convention)", 9, (0.16, 0.34, 0.46))
    for index, bend in enumerate(packet["bendMappings"]):
        content += pdf_text(42, 207 - index * 16, bend["bendId"] + "     90 deg     Signed fold rotation " + f"{bend['foldRotationDeg']:+.0f}" + " deg", 9)
    content += pdf_text(42, 94, "Step order: " + "  >  ".join(packet["stepOrder"]), 9)
    content += pdf_text(42, 72, "Rigid-panel diagram excludes bend radii, springback, collision and press-brake motion.", 8, (0.39, 0.43, 0.46))
    content += pdf_text(42, 48, "Original synthetic artwork for the SkunkWorks prototype. Not an engineering release.", 8, (0.39, 0.43, 0.46))
    stream = content.encode("ascii")

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Length " + str(len(stream)).encode("ascii") + b" >>\nstream\n" + stream + b"endstream",
    ]
    output = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for object_number, obj in enumerate(objects, start=1):
        offsets.append(len(output))
        output.extend(f"{object_number} 0 obj\n".encode("ascii"))
        output.extend(obj)
        output.extend(b"\nendobj\n")
    xref_offset = len(output)
    output.extend(f"xref\n0 {len(offsets)}\n".encode("ascii"))
    output.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.extend(f"{offset:010d} 00000 n \n".encode("ascii"))
    output.extend(f"trailer\n<< /Size {len(offsets)} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF\n".encode("ascii"))
    path.write_bytes(output)


def main() -> None:
    for variant_id in ("alpha", "bravo"):
        packet = variant(variant_id)
        prefix = OUTPUT / ("sensor-mount-" + variant_id)
        (prefix.with_suffix(".bend.json")).write_text(json.dumps(packet, indent=2) + "\n", encoding="utf-8")
        make_pdf(packet, Path(str(prefix) + ".drawing.pdf"))
        write_glb(Path(str(prefix) + ".final.glb"), packet)
        print(str(prefix) + " generated")


if __name__ == "__main__":
    main()
